# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Carolyn Tiry
tagline:
description:      Coffee. Code. Repeat.
url:              http://carolyntiry.github.io
baseurl:          /

author:
  name:           'Carolyn Tiry'
  url:            https://twitter.com/carolyntiry
  email:          'carolyntiry[at]gmail[dot]com'
  github:         carolyntiry
  twitter:        carolyntiry
  linkedin:       carolyntiry
  goodreads:      carolyntiry
  google_analytics_id: UA-74071611-1
  google_analytics_url: carolyntiry.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/carolyntiry/carolyntiry.github.io
