# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Carolyn Tiry
tagline:          
description:      
url:              http://carolyntiry.github.io
baseurl:          /

author:
  name:           'Carolyn Tiry'
  url:            https://twitter.com/carolyntiry
  email:          'carolyntiry[at]gmail[dot]com'
  github:         carolyntiry
  twitter:        carolyntiry
  linkedin:       carolyntiry
  goodreads:      carolyntiry

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/carolyntiry/carolyntiry.github.io
